baseURL = "https://www.pigaunt.top"
languageCode = "zh-CN"
title = "PigAunt的博客"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

preserveTaxonomyNames = true
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

[author]
  name = "PigAunt"

[params]
  author = "PigAunt"
  subtitle = "Hello, World!"
  keywords = "C++,OI,C#"
  description = "PigAunt的博客"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true

  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 友情链接，可以多个
[[params.links]]
  title = "RuSun的博客"
  name = "RuSun的博客"
  url = "https://rusun.blog.luogu.org/"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
  name = "知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议"
  ink = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "dracula"

## 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 1
   [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2